# Data

In [1]:
from tqdm import tqdm

In [2]:
data=[i for i in tqdm(range(55000))]

100%|██████████| 55000/55000 [00:00<00:00, 1448373.05it/s]


In [3]:
n_seq=2
predict=1

In [4]:
def sequence_creator(data,n_seq=5,predict=2):
  import numpy as np
  x=[]
  y=[]

  for i in tqdm(range(len(data))):
    last=i+n_seq
    if last>=len(data)-1:break
    x.append(data[i:last])
    y.append(data[last:last+predict])
  return np.array(x),np.array(y)

In [5]:
x,y=sequence_creator(data,n_seq,predict)

100%|█████████▉| 54997/55000 [00:00<00:00, 295472.04it/s]


In [6]:
t_data=[i for i in tqdm(range(55000,65000))]

100%|██████████| 10000/10000 [00:00<00:00, 2010981.45it/s]


In [7]:
y_test,y_label=sequence_creator(t_data,n_seq,predict)

100%|█████████▉| 9997/10000 [00:00<00:00, 634080.22it/s]


## Tensor Board


In [8]:
# Clear any logs from previous runs
!rm -rf ./logs/

In [9]:
import datetime
log_dir = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = keras.callbacks.TensorBoard(log_dir=log_dir, histogram_freq=1)

NameError: ignored

# Model

In [11]:
from tensorflow import keras
from keras.layers import Dense,LSTM,Normalization
from keras.models import Sequential
import numpy as np


In [12]:
lstm=Sequential()

In [13]:
x.shape[0],x.shape[1]

(54997, 2)

In [14]:
lstm.add(LSTM(50,activation='relu', input_shape=(x.shape[1],1)))
# lstm.add(LSTM(30,activation='relu',return_sequences=True,))
# lstm.add(LSTM(30,activation='relu', return_sequences=True,))
# lstm.add(LSTM(30,activation='relu',return_sequences=True,))
# lstm.add(LSTM(30,activation='relu'))
lstm.add(Dense(1))
lstm._name='practise_Lstm'

In [15]:
lstm.compile(optimizer='adam',loss='mse')

In [16]:
lstm.fit(x,y,epochs=10)

Epoch 1/10
1719/1719 [==============================] - 7s 3ms/step - loss: 47342876.0000
Epoch 2/10
1719/1719 [==============================] - 5s 3ms/step - loss: 0.1073
Epoch 3/10
1719/1719 [==============================] - 5s 3ms/step - loss: 0.1011
Epoch 4/10
1719/1719 [==============================] - 5s 3ms/step - loss: 0.1010
Epoch 5/10
1719/1719 [==============================] - 5s 3ms/step - loss: 0.1048
Epoch 6/10
1719/1719 [==============================] - 5s 3ms/step - loss: 2.1662
Epoch 7/10
1719/1719 [==============================] - 6s 3ms/step - loss: 92.5150
Epoch 8/10
1719/1719 [==============================] - 5s 3ms/step - loss: 115.7050
Epoch 9/10
1719/1719 [==============================] - 5s 3ms/step - loss: 77.6906
Epoch 10/10
1719/1719 [==============================] - 6s 3ms/step - loss: 197.4227


In [17]:
y_test

array([[55000, 55001],
       [55001, 55002],
       [55002, 55003],
       ...,
       [64994, 64995],
       [64995, 64996],
       [64996, 64997]])

In [18]:
lstm.evaluate(y_test,y_label)

313/313 [==============================] - 1s 2ms/step - loss: 0.0029


0.002918200334534049

# Predict

In [22]:
p=np.arange(9000,9002,1).reshape(1,2,1)
p

array([[[9000],
        [9001]]])

In [23]:
lstm.predict(p)

array([[9001.776]], dtype=float32)

In [ ]:
lstm.summary()